services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ///
      POSTGRES_PASSWORD: ///
      POSTGRES_DB: ///
    ports:
      - "0000:0000"


  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=///
      - POSTGRES_PASSWORD=///
      - POSTGRES_DB=///
      - SECRET_KEY=///
    depends_on:
      - db



